const { OpenAI } = require('openai');
require('dotenv').config();

// Initialize OpenAI API
const openai = new OpenAI({
    apiKey: process.env.openai_api_key,
});

/**
 * Function to generate patient notes using OpenAI API
 * @param {string} originalText - The original script
 * @returns {Promise<string>} - The patient notes from OpenAI
 */
const generatePatientNotes = async (originalText) => {
    const prePrompt = `Please use this transcription of a patient-doctor interaction to generate organized patient notes. First you should refine this text, then generate the organized patient notes based on the refined text. The organized patient notes MUST follow this structure:
    Subjective (S): Include the patient's chief complaint, history of present illness, past medical history, and any relevant social/family history or review of systems mentioned in the conversation.
    Objective (O): Extract any physical exam findings, lab results, imaging, or other objective data that the doctor discusses.
    Assessment (A): Summarize the doctor's assessment, including the diagnosis or possible differential diagnoses.
    Plan (P): Detail the treatment plan, any follow-up instructions, and patient education provided by the doctor. Please do not include any other text, and just directly give me these organized patient notes in bullet point format. Becuase you are using bullet point format, do not use bullet points within the contents. 
    The example has ended, only add newlines to separate each of the described sections above, otherwise do not add any newline character. Do not hallucinate and do not make up anything else that is not present within the following text. Remember to write these notes from the perspective of the doctor who is writing notes for other doctors and nurses who are working with the patient to see. Here is an example of what your response should look like, note that the contents of this are an example only for structure so ignore the contents: Subjective (S):\n- Chief complaint: Persistent headache for about a week, feeling more tired than usual\n- History of present illness: Dull ache located at the front of the head, above the eyes, making it hard to concentrate, rated the pain at a 4 or 5 out of 10\n- Past medical history: Mild cold 2 weeks ago\n- Social/family history: Sleeping 7 to 8 hours a night but still waking up feeling exhausted\n\nObjective (O):\n- Sinus tenderness on physical exam around the cheeks\n- Possible sinus congestion contributing to headache\n\nAssessment (A):\n- Sinus congestion leading to headache\n\nPlan (P):\n- Recommend saline nasal spray to clear sinuses\n- Decongestant (like pseudoephedrine) for a few days\n- Stay hydrated and use a humidifier at night\n- Avoid caffeine or alcohol\n- Follow up in a week to check on symptoms\n- Encouraged to call if any issues arise before next appointment
    The example is done, the following text was generated by a speech-to-text model:
    \n\n"${originalText}"`;

    // Call OpenAI API
    const response = await openai.chat.completions.create({
        model: 'gpt-3.5-turbo-0125',
        messages: [{ role: 'user', content: prePrompt }],
    });

    // Return the patient notes
    return response.choices[0].message.content.trim();
};

module.exports = { generatePatientNotes };
