const { OpenAI } = require('openai');
require('dotenv').config();

// Initialize OpenAI API
const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

/**
 * Function to generate patient notes using OpenAI API
 * @param {string} originalText - The original script
 * @returns {Promise<string>} - The patient notes from OpenAI
 */
const generatePatientNotes = async (originalText) => {
    const prePrompt = `Please use this transcription of a patient-doctor interaction to generate organized patient notes. First you should refine this text, then generate the organized patient notes based on the refined text. The organized patient notes MUST follow this structure:
    Subjective (S): Include the patient's chief complaint, history of present illness, past medical history, and any relevant social/family history or review of systems mentioned in the conversation.
    Objective (O): Extract any physical exam findings, lab results, imaging, or other objective data that the doctor discusses.
    Assessment (A): Summarize the doctor's assessment, including the diagnosis or possible differential diagnoses.
    Plan (P): Detail the treatment plan, any follow-up instructions, and patient education provided by the doctor. Please do not include any other text, and just directly give me these organized patient notes in bullet point format. Becuase you are using bullet point format, do not use bullet points within the contents.
    Only add newlines to separate each of the described sections above, otherwise do not add any newline character. Do not hallucinate and do not make up anything else that is not present within the following text. Remember to write these notes from the perspective of the doctor who is writing notes for other doctors and nurses who are working with the patient to see.
    This text was generated by a speech-to-text model:
    \n\n"${originalText}"`;

    // Call OpenAI API
    const response = await openai.chat.completions.create({
        model: 'gpt-3.5-turbo-0125',
        messages: [{ role: 'user', content: prePrompt }],
    });

    // Return the patient notes
    return response.choices[0].message.content.trim();
};

module.exports = { generatePatientNotes };
