services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - grammateus-network
    depends_on:
      - backend
    command: npm start
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npx nodemon --legacy-watch index.js
    networks:
      - grammateus-network
    env_file:
      - ./backend/.env

networks:
  grammateus-network:
