apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: my-app
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: wongsamuel02/grammateus-backend:2.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-env
        # env:
        # - name: mongodb_uri
        #   value: "mongodb+srv://wongsamuel02:tTniMB8d5JbXFCKm@grammateus.0yrfv.mongodb.net/Grammateus?retryWrites=true&w=majority&appName=Grammateus"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: my-app
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
